language: python

env:
  - TOXENV=django19

install:
  - pip install tox
  - pip install coveralls

before_script:
  - psql -U postgres -c "create database jmbo encoding 'UTF8'"

script:
  - tox

after_success:
  - coveralls
