# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import simplemde.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jmbo', '0005_modelbase_layers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jmbo.ModelBase')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
            },
            bases=('jmbo.modelbase',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('parent_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='jmbo.ModelBase')),
                ('external_link', models.CharField(blank=True, help_text=b"The url of the event's external webpage, if there is one.", max_length=255, null=True)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('repeat', models.CharField(choices=[(b'does_not_repeat', b'Does Not Repeat'), (b'daily', b'Daily'), (b'weekdays', b'Weekdays'), (b'weekends', b'Weekends'), (b'weekly', b'Weekly'), (b'monthly_by_day_of_month', b'Monthly By Day Of Month')], default=b'does_not_repeat', max_length=64)),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('content', simplemde.fields.SimpleMDEField(help_text=b'The event description.')),
                ('calendars', models.ManyToManyField(blank=True, null=True, related_name='event_calendars', to='jmbo_calendar.Calendar')),
            ],
            options={
                'ordering': ('start',),
            },
            bases=('jmbo.modelbase',),
        ),
    ]
